apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  MONGODB_URI: "mongodb://admin:password@mongodb-service:27017/amazona?authSource=admin"
  PORT: "5000"
  NODE_ENV: "production"
  REACT_APP_API_URL: "https://your-domain.com"  # Update this with your actual domain
  JWT_SECRET: "somethingsecret"
  PAYPAL_CLIENT_ID: "sb"
  AWS_REGION: "us-east-1"
  AWS_BUCKET_NAME: "amazona20"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded AWS credentials
  # To encode: echo -n 'your-access-key' | base64
  AWS_ACCESS_KEY_ID: "eW91ci1hd3MtYWNjZXNzLWtleS1pZA=="  # your-aws-access-key-id (base64)
  AWS_SECRET_ACCESS_KEY: "eW91ci1hd3Mtc2VjcmV0LWFjY2Vzcy1rZXk="  # your-aws-secret-access-key (base64)
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4="  # admin (base64)
  MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQ="  # password (base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: ecommerce
type: kubernetes.io/dockerconfigjson
data:
  # Replace with your Docker Hub credentials
  # To create this secret, run:
  # kubectl create secret docker-registry dockerhub-secret \
  #   --docker-server=https://index.docker.io/v1/ \
  #   --docker-username=YOUR_DOCKERHUB_USERNAME \
  #   --docker-password=YOUR_DOCKERHUB_PASSWORD \
  #   --docker-email=YOUR_EMAIL \
  #   --namespace=ecommerce \
  #   --dry-run=client -o yaml | grep '\.dockerconfigjson:' | cut -d':' -f2 | tr -d ' '
  .dockerconfigjson: "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJZT1VSX0RPQ0tFUkhVQl9VU0VSTkFNRSIsInBhc3N3b3JkIjoiWU9VUl9ET0NLRVJIVUJfUEFTU1dPUkQiLCJlbWFpbCI6IllPVVJfRU1BSUwiLCJhdXRoIjoiV1U5VlVsOUVUME5MUlZKSVZVSmZWVk5GVWs1QlRVVTZXVTlWVWw5RVQwTkxSVkpJVlVKZlVFRlRVMWRQVWtRPSJ9fX0="
